name: Peru 2014
markdown: redcarpet
pygments: false
destination: _site
exclude: [
	"node_modules",
	"sources",
	".sass-cache",
	"sass"
]
timezone: Europe/Amsterdam
permalink: /:title
baseurl:  /
url: http://peru2014.nl/